services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    entrypoint: /bin/bash
    command: >
      -c "envsubst < /config/wg0.conf.template > /config/wg0.conf && exec /init"
    env_file:
      - .env
    restart: unless-stopped
